# Run scripts by release

name: Release

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get python's version
        run: python2 --version

      - name: Run release
        run: echo Run!      
        
